name: Parkee Archive

on:
  schedule:
    - cron: '0 16 * * 1-5'
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright
        run: |
          npm init -y
          npm install playwright

      - name: Install Chromium
        run: npx playwright install chromium

      - name: Run Script
        run: node capture.js

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: parkee-archive
          path: output/