name: Parkee Download

on:
  schedule:
    - cron: '0 16 * * 1-5'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browser
        run: npx playwright install chromium

      - name: Run automation
        env:
          OUTLOOK_EMAIL: ${{ secrets.OUTLOOK_EMAIL }}
          OUTLOOK_PASSWORD: ${{ secrets.OUTLOOK_PASSWORD }}
        run: node download.js

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: parkee-download
          path: output/